sudo: false
language: rust
cache: cargo

rust: stable

before_install:
  - |
      if ! hash cargo-tree 2>/dev/null; then
          cargo install cargo-tree --debug
      fi
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  # Fail if there are any duplicate dependencies
  - "[[ ! $(cargo tree -d | tee /dev/fd/2 ) ]]"

# Copied from cargo-tree's .travis.yml
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
