[package]
name = "stdx"
version = "0.115.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "The missing batteries of Rust"
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "=0.7.0"
clap = "=2.20.0"
env_logger = "=0.4.0"
itertools = "=0.5.9"
lazy_static = "=0.2.2"
libc = "=0.2.18"
log = "=0.3.6"
num = "=0.1.36"
rand = "=0.3.15"
regex = "=0.2.1"
rustc-serialize = "=0.3.22"
semver = "=0.5.1"
tempdir = "=0.3.5"
time = "=0.1.36"
toml = "=0.2.1"
url = "=1.3.0"
