[package]
name = "stdx"
version = "0.107.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "The missing batteries of Rust"
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "=0.5.0"
docopt = "=0.6.78"
env_logger = "=0.3.2"
itertools = "=0.4.10"
lazy_static = "=0.1.15"
libc = "=0.2.7"
log = "=0.3.5"
num = "=0.1.31"
rand = "=0.3.14"
regex = "=0.1.55"
rustc-serialize = "=0.3.18"
semver = "=0.2.3"
tempdir = "=0.3.4"
time = "=0.1.34"
toml = "=0.1.27"
url = "=0.5.5"
