[package]
name = "stdx"
version = "0.0.1"
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "The missing batteries of Rust"
license = "MIT/Apache-2.0"

[features]
default = [
    "bitflags",
    "docopt",
    "env_logger",
    "itertools",
    "lazy_static",
    "libc",
    "log",
    "num",
    "rand",
    "regex",
    "rustc-serialize",
    "semver",
    "tempdir",
    "time",
    "toml",
    "url",
]
all = ["default", "flate2", "hyper"]

[dependencies]
bitflags = { version = "0.5.0", optional = true }
docopt = { version = "0.6.78", optional = true }
env_logger = { version = "0.3.2", optional = true }
flate2 = { version = "0.2.13", optional = true }
hyper = { version = "0.7.2", optional = true }
itertools = { version = "0.4.10", optional = true }
lazy_static = { version = "0.1.15", optional = true }
libc = { version = "0.2.7", optional = true }
log = { version = "0.3.5", optional = true }
num = { version = "0.1.31", optional = true }
rand = { version = "0.3.14", optional = true }
regex = { version = "0.1.15", optional = true }
rustc-serialize = { version = "0.3.18", optional = true }
semver = { version = "0.2.3", optional = true }
tempdir = { version = "0.3.4", optional = true }
time = { version = "0.1.34", optional = true }
toml = { version = "0.1.27", optional = true }
url = { version = "0.5.5", optional = true }
