[package]
name = "stdx"
version = "0.117.0-rc"
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "The missing batteries of Rust"
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "0.9.0"
byteorder = "1.0.0"
chrono = { version = "0.3.1", features = ["serde"] }
clap = "2.24.2"
error-chain = "0.10.0"
json = "0.11.6"
lazy_static = "0.2.8"
libc = "0.2.23"
log = "0.3.7"
ndarray = { version = "0.9.1", features = ["serde"] }
num = "0.1.37"
rand = "0.3.15"
rayon = "0.7.0"
regex = "0.2.2"
reqwest = "0.6.2"
serde = "1.0.7"
tempdir = "0.3.5"
toml = "0.4.1"
url = "1.4.0"

# Supplemental dependencies
env_logger = "0.4.2"
serde_derive = "1.0.7"
serde_json = "1.0.2"
